<?php namespace Rebel59\MixManifest;

use Backend;
use System\Classes\PluginBase;

/**
 * MixManifest Plugin Information File
 */
class Plugin extends PluginBase
{
    /**
     * Returns information about this plugin.
     *
     * @return array
     */
    public function pluginDetails()
    {
        return [
            'name'        => 'Mix Manifest',
            'description' => 'Provides twig function to read the manifest file generated by Laravel Mix Versioning',
            'author'      => 'Rebel59',
            'homepage'    => 'https://rebel59.nl',
            'icon'        => 'icon-leaf'
        ];
    }

    public function registerMarkupTags()
    {
        return [
            'functions' => [
                'getVersionedCss' => [$this, 'readManifest']
            ]
        ];
    }

    public function readManifest($path, $prefix = '/assets')
    {
        $loc = env('MANIFEST_PATH');
        $manifest = file_get_contents($loc);

        $manifest = json_decode($manifest);
        $themePath = Config::get('app.url') . Config::get('cms.themesPath') . "/" . Config::get('cms.activeTheme');

        return $themePath . $prefix . $manifest->$path;
    }
}
